#! /bin/sh


RED=#93503e
GRN=#7a8648
YLW=#9d8554
CYN=#566e6b
WHT=#aaaaaa
BRN=#9b7059
CHR=#9a6d40
LGR=#72765b
DGR=#5f5e6c
MAG=#7b6064
SEP=" "
TAB="   "
LOA="\uf200"
FAN="\uf0e4"
MEM="\uf1c0"
TMP="\uf06d"
VOL="\uf028"
PAC="\uf284"
DAT="\uf073"
CLK="\uf017"
WIN="\uf009"
GRS="\uf085"
DRV="\uf0a0"
CRM="\uf268"

home(){
	echo "$(df -hl | grep data | sed 's/ \+/ /g' | cut -d' ' -f5)"
}

root(){
	echo "$(df -hl /home | grep "/" | sed 's/ \+/ /g' | cut -d' ' -f5)"
}

while true; do
	echo -e "%{c}%{F$DGR}$DRV$SEP$(root)%{F-}$TAB%{F$LGR}$DRV$SEP$(home)%{F-}"
	sleep 60
done
