#! /bin/sh

RED=#93503e
GRN=#7a8648
YLW=#9d8554
CYN=#566e6b
WHT=#aaaaaa
STH=#977D5E
BRN=#9b7059
CHR=#9a6d40
LGR=#72765b
DGR=#5f5e6c
MAG=#7b6064
SEP=" "
TAB="   "
CPU="\uf0e4"
MEM="\uf1c0"
TMP="\uf06d"
VOL="\uf028"
PAC="\uf284"
DAT="\uf073"
CLK="\uf017"
WIN="\uf009"
GRS="\uf085"
DRV="\uf0a0"
CRM="\uf268"

pac() {
	echo "$(checkupdates | wc -l)"
}

while true; do
	echo -e "%{c}%{F$STH}$PAC$SEP$(pac)%{F-}"
	sleep 60
done
