#! /bin/sh

W="1300"
H="30"
O="30"

bspc config history_aware_focus		false
bspc config border_width       	 	1
bspc config window_gap         		30
bspc config split_ratio         	0.5
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true
bspc config focus_follows_pointer	true
bspc config normal_border_color		"#383836"
bspc config focused_border_color 	"#9b3e57" #cold
bspc config presel_feedback_color       "#9b3e57"
bspc config top_padding                 60
bspc config left_padding                800
bspc config right_padding               800
bspc config bottom_padding              60

bspc monitor DP-2 -d 0 1 2 3 4 5 6 7 8 9

bspc rule -a *:chromium desktop='^8' follow=on
bspc rule -a *:gimp desktop='^10' follow=on state=floating
bspc rule -a *:feh state=floating

feh --bg-scale ~/data/Wallpapers/cold.png &> /dev/null &
~/.config/bspwm/panel/top_panel &
~/.config/bspwm/panel/bottom_panel &

~/.config/bspwm/home_neo_launch

wget -q --spider https://www.archlinux.org/news/ 

while ! [ $? -eq 0 ]; do
    sleep 1
    wget -q --spider https://www.archlinux.org/news/ 
done

# Note: sleeping (delay) is absolutely necessary between window calls to enforce the correct order of windows.
bspc rule -a *:urxvt -o state=floating locked=on rectangle=700x870+650+285 && urxvt -hold -e ncmpcpp -s playlist &
sleep 0.5
bspc rule -a *:urxvt -o state=floating locked=on rectangle=700x500+1370+655 && urxvt -hold -e ncmpcpp -s visualizer &
sleep 0.5
bspc rule -a *:urxvt -o state=floating locked=on rectangle=700x870+2090+285 && urxvt --hold -e w3m https://www.archlinux.org/news/ &
