#! /bin/sh

pkill -f 'urxvt -hold -e neofetch --size 32% --gap 8'
xrdb ~/.Xresources_home
bspc desktop -f ^1
sleep 0.05
bspc rule -a *:urxvt -o state=floating focus=on locked=on rectangle=700x350+1370+285 && urxvt -hold -e neofetch --size 32% --gap 8 &
sleep 0.5
xrdb ~/.Xresources
